runtime: python27
threadsafe: yes
api_version: 1

inbound_services:
- warmup

handlers:
- url: /bower_components
  static_dir: bower_components
  secure: always
  login: admin

- url: /src/common-worker-scope.js
  static_files: bower_components/app-storage/app-indexeddb-mirror/common-worker-scope.js
  upload: bower_components/app-storage/app-indexeddb-mirror/common-worker-scope.js
  secure: always
  login: admin

- url: /src/bower_components/.*
  static_files: empty.html
  upload: empty.html
  secure: always
  login: admin

- url: /images
  static_dir: images
  secure: always
  login: admin

- url: /scripts
  static_dir: scripts
  secure: always
  login: admin

- url: /src/src/.*
  static_files: empty.html
  upload: empty.html
  secure: always
  login: admin

- url: /src
  static_dir: src
  secure: always
  login: admin

- url: /index.html
  static_files: index.html
  upload: index.html
  login: admin
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always

- url: /sw-notifications.js
  static_files: sw-notifications.js
  upload: sw-notifications.js
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  login: admin
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  login: admin
  secure: always


skip_files:
- ^bower_components/(.*/)?.*\.md$
- ^bower_components/(.*/)?.*\.test$
- ^bower_components/(.*/)?test/.*
- ^bower_components/(.*/)?Makefile$
- ^bower_components/(.*/)?LICENSE$
- ^bower_components/(.*/)?COPYING$

